In [1]:
import numpy as np
import pandas as pd

from sklearn.metrics import mean_squared_error

### Regression

In [2]:
data_X = np.arange(10).reshape(-1, 1).astype('float32')
data_Y = np.arange(10).reshape(-1, 1).astype('float32')

In [3]:
from sklearn import model_selection

train_X, test_X, train_Y, test_Y = model_selection.train_test_split\
(data_X, data_Y, test_size=0.3, random_state=0)
print(train_X.shape)
print(test_X.shape)
print(train_X)

(7, 1)
(3, 1)
[[9.]
 [1.]
 [6.]
 [7.]
 [3.]
 [0.]
 [5.]]


In [4]:
import tensorflow as tf
from tensorflow.keras import models, layers, activations, initializers, \
losses, optimizers, metrics
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'


In [17]:
model = models.Sequential() 

model.add(layers.Dense(input_dim=1, units=128, activation=None)) 
# model.add(layers.BatchNormalization()) # Use this line as if needed
model.add(layers.Activation('relu')) # layers.ELU or layers.LeakyReLU

model.add(layers.Dense(units=128, activation=None)) 
model.add(layers.Activation('relu'))

model.add(layers.Dense(units=64, activation=None)) 
model.add(layers.Activation('relu'))
# model.add(layers.Dropout(rate=0.4))

model.add(layers.Dense(units=1, activation=None))

In [18]:
model.compile(optimizer=optimizers.Adam(),
              loss=losses.mean_squared_error,
              metrics=[metrics.mean_squared_error])

In [20]:
history = model.fit(train_X, train_Y, batch_size=6, epochs=5, verbose=1)

Epoch 1/5
7/7 [==============================] - 0s 1ms/sample - loss: 1.0035 - mean_squared_error: 1.0035
Epoch 2/5
7/7 [==============================] - 0s 570us/sample - loss: 0.0532 - mean_squared_error: 0.0532
Epoch 3/5
7/7 [==============================] - 0s 570us/sample - loss: 0.1304 - mean_squared_error: 0.1304
Epoch 4/5
7/7 [==============================] - 0s 135us/sample - loss: 0.7593 - mean_squared_error: 0.7593
Epoch 5/5
7/7 [==============================] - 0s 1ms/sample - loss: 1.2219 - mean_squared_error: 1.2219


In [21]:
result = model.evaluate(test_X, test_Y)

print('loss (mse) :', result[0])

3/3 [==============================] - 0s 27ms/sample - loss: 0.9956 - mean_squared_error: 0.9956
loss (mse) : 0.9955857396125793


In [22]:
pred_X = np.array([11, 12, 13]).reshape(-1, 1)

In [23]:
model.predict(pred_X)

array([[12.9005575],
       [14.055028 ],
       [15.2095   ]], dtype=float32)

### Classifier

In [ ]:
from keras.utils import to_categorical

In [ ]:
data_X = np.arange(10).reshape(-1, 1)
# .astype('float32')
data_Y = to_categorical([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

train_X, test_X, train_Y, test_Y = model_selection.train_test_split\
(data_X, data_Y, test_size=0.3, random_state=0)
print(train_X.shape)
print(test_X.shape)
print(test_Y.shape)


In [31]:
model = models.Sequential() 

model.add(layers.Dense(input_dim=1, units=64, activation=None)) 
# model.add(layers.BatchNormalization()) # Use this line as if needed
model.add(layers.Activation('relu')) # layers.ELU or layers.LeakyReLU

model.add(layers.Dense(units=128, activation=None)) 
model.add(layers.Activation('relu')) 

model.add(layers.Dense(units=64, activation=None)) 
model.add(layers.Activation('relu'))

model.add(layers.Dense(units=2, activation='softmax')) # One-hot vector for 0 & 1

In [32]:
model.compile(optimizer=optimizers.Adam(), 
              loss=tf.losses.sigmoid_cross_entropy,
              metrics=[metrics.binary_accuracy]) 

In [34]:
history = model.fit(train_X, train_Y, batch_size=6, epochs=10, verbose=1)

Epoch 1/10
7/7 [==============================] - 0s 0s/sample - loss: -1.2402 - binary_accuracy: 0.1429
Epoch 2/10
7/7 [==============================] - 0s 0s/sample - loss: -1.2402 - binary_accuracy: 0.1429
Epoch 3/10
7/7 [==============================] - 0s 427us/sample - loss: -1.2402 - binary_accuracy: 0.1429
Epoch 4/10
7/7 [==============================] - 0s 427us/sample - loss: -1.2402 - binary_accuracy: 0.1429
Epoch 5/10
7/7 [==============================] - 0s 427us/sample - loss: -1.2402 - binary_accuracy: 0.1429
Epoch 6/10
7/7 [==============================] - 0s 35us/sample - loss: -1.2402 - binary_accuracy: 0.1429
Epoch 7/10
7/7 [==============================] - 0s 318us/sample - loss: -1.2402 - binary_accuracy: 0.1429
Epoch 8/10
7/7 [==============================] - 0s 637us/sample - loss: -1.2402 - binary_accuracy: 0.1429
Epoch 9/10
7/7 [==============================] - 0s 570us/sample - loss: -1.2402 - binary_accuracy: 0.1429
Epoch 10/10
7/7 [==================

In [35]:
result = model.evaluate(test_X, test_Y)

print('loss (cross-entropy) :', result[0])
print('test accuracy :', result[1])

3/3 [==============================] - 0s 22ms/sample - loss: -1.3593 - binary_accuracy: 0.0000e+00
loss (cross-entropy) : -1.359256386756897
test accuracy : 0.0


In [36]:
pred_X = np.array([11, 12, 13]).reshape(-1, 1)

In [37]:
np.argmax(model.predict(test_X), axis=1)

array([0, 0, 1], dtype=int64)

#### Classifier2

In [ ]:
from keras.utils import np_utils

data_X = np.arange(10).reshape(-1, 1).astype('float32')
data_Y = np.array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5]).astype('float32')
data_Y = np_utils.to_categorical(data_Y, 6)
print(data_Y)

In [ ]:
train_X, test_X, train_Y, test_Y = model_selection.train_test_split\
(data_X, data_Y, test_size=0.3, random_state=0)
print(train_X.shape)
print(test_X.shape)
print(test_Y.shape)
print(test_Y)

In [ ]:
model = models.Sequential() 

model.add(layers.Dense(input_dim=1, units=64, activation=None)) 
# model.add(layers.BatchNormalization()) # Use this line as if needed
model.add(layers.Activation('relu')) # layers.ELU or layers.LeakyReLU

model.add(layers.Dense(units=64, activation=None)) 
model.add(layers.Activation('relu')) 

model.add(layers.Dense(units=32, activation=None)) 
model.add(layers.Activation('relu'))

model.add(layers.Dense(units=6, activation='softmax')) # One-hot vector for 0 & 1

In [ ]:
model.compile(optimizer=optimizers.Adam(), 
              loss='categorical_crossentropy',
              metrics=[metrics.categorical_accuracy]) 

In [ ]:
history = model.fit(train_X, train_Y, batch_size=3, epochs=5, verbose=0)

In [ ]:
result = model.evaluate(test_X, test_Y)

print('loss (cross-entropy) :', result[0])
print('test accuracy :', result[1])

In [ ]:
pred_X = np.array([11, 12, 13]).reshape(-1, 1)

In [ ]:
np.argmax(model.predict(test_X), axis=1)