In [1]:
import numpy as np
import pandas as pd

from sklearn.metrics import mean_squared_error

### Regression

In [142]:
data_X = np.arange(10).reshape(-1, 1).astype('float32')
data_Y = np.arange(10).reshape(-1, 1).astype('float32')

In [143]:
from sklearn import model_selection

train_X, test_X, train_Y, test_Y = model_selection.train_test_split\
(data_X, data_Y, test_size=0.3, random_state=0)
print(train_X.shape)
print(test_X.shape)
print(train_X)

(7, 1)
(3, 1)
[[9.]
 [1.]
 [6.]
 [7.]
 [3.]
 [0.]
 [5.]]


In [144]:
import tensorflow as tf
from tensorflow.keras import models, layers, activations, initializers, \
losses, optimizers, metrics
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'


In [151]:
model = models.Sequential() 

model.add(layers.Dense(input_dim=1, units=128, activation=None)) 
# model.add(layers.BatchNormalization()) # Use this line as if needed
model.add(layers.Activation('relu')) # layers.ELU or layers.LeakyReLU

model.add(layers.Dense(units=128, activation=None)) 
model.add(layers.Activation('relu'))

model.add(layers.Dense(units=64, activation=None)) 
model.add(layers.Activation('relu'))
# model.add(layers.Dropout(rate=0.4))

model.add(layers.Dense(units=1, activation=None))

In [152]:
model.compile(optimizer=optimizers.Adam(),
              loss=losses.mean_squared_error,
              metrics=[metrics.mean_squared_error])

In [158]:
history = model.fit(train_X, train_Y, batch_size=6, epochs=100, verbose=1)

Epoch 1/100
7/7 [==============================] - 0s 0s/sample - loss: 2.2291 - mean_squared_error: 2.2291
Epoch 2/100
7/7 [==============================] - 0s 570us/sample - loss: 1.0634 - mean_squared_error: 1.0634
Epoch 3/100
7/7 [==============================] - 0s 570us/sample - loss: 0.2903 - mean_squared_error: 0.2903
Epoch 4/100
7/7 [==============================] - 0s 532us/sample - loss: 0.0287 - mean_squared_error: 0.0287
Epoch 5/100
7/7 [==============================] - 0s 1ms/sample - loss: 0.2004 - mean_squared_error: 0.2004
Epoch 6/100
7/7 [==============================] - 0s 428us/sample - loss: 0.4337 - mean_squared_error: 0.4337
Epoch 7/100
7/7 [==============================] - 0s 570us/sample - loss: 0.5824 - mean_squared_error: 0.5824
Epoch 8/100
7/7 [==============================] - 0s 570us/sample - loss: 0.5428 - mean_squared_error: 0.5428
Epoch 9/100
7/7 [==============================] - 0s 712us/sample - loss: 0.3587 - mean_squared_error: 0.3587
Epoch 

7/7 [==============================] - 0s 712us/sample - loss: 2.7594e-04 - mean_squared_error: 2.7594e-04
Epoch 74/100
7/7 [==============================] - 0s 570us/sample - loss: 1.8236e-04 - mean_squared_error: 1.8236e-04
Epoch 75/100
7/7 [==============================] - 0s 570us/sample - loss: 2.1265e-04 - mean_squared_error: 2.1265e-04
Epoch 76/100
7/7 [==============================] - 0s 427us/sample - loss: 2.3029e-04 - mean_squared_error: 2.3029e-04
Epoch 77/100
7/7 [==============================] - 0s 570us/sample - loss: 1.1757e-04 - mean_squared_error: 1.1757e-04
Epoch 78/100
7/7 [==============================] - 0s 570us/sample - loss: 2.8494e-04 - mean_squared_error: 2.8494e-04
Epoch 79/100
7/7 [==============================] - 0s 570us/sample - loss: 1.3021e-04 - mean_squared_error: 1.3021e-04
Epoch 80/100
7/7 [==============================] - 0s 570us/sample - loss: 2.9131e-04 - mean_squared_error: 2.9131e-04
Epoch 81/100
7/7 [==============================] - 0

In [159]:
result = model.evaluate(test_X, test_Y)

print('loss (mse) :', result[0])

3/3 [==============================] - 0s 0s/sample - loss: 3.4395e-04 - mean_squared_error: 3.4395e-04
loss (mse) : 0.0003439505526330322


In [160]:
pred_X = np.array([11, 12, 13]).reshape(-1, 1)

In [161]:
model.predict(pred_X)

array([[11.00398 ],
       [12.001164],
       [12.998347]], dtype=float32)

### Classifier

In [40]:
from keras.utils import to_categorical

Using TensorFlow backend.


In [163]:
data_X = np.arange(10).reshape(-1, 1)
# .astype('float32')
data_Y = to_categorical([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

train_X, test_X, train_Y, test_Y = model_selection.train_test_split\
(data_X, data_Y, test_size=0.3, random_state=0)
print(train_X.shape)
print(test_X.shape)
print(test_Y.shape)



(7, 1)
(3, 1)
(3, 2)


In [168]:
model = models.Sequential() 

model.add(layers.Dense(input_dim=1, units=128, activation=None)) 
# model.add(layers.BatchNormalization()) # Use this line as if needed
model.add(layers.Activation('relu')) # layers.ELU or layers.LeakyReLU

model.add(layers.Dense(units=128, activation=None)) 
model.add(layers.Activation('relu')) 

model.add(layers.Dense(units=64, activation=None)) 
model.add(layers.Activation('relu'))

model.add(layers.Dense(units=2, activation='softmax')) # One-hot vector for 0 & 1

In [169]:
model.compile(optimizer=optimizers.Adam(), 
              loss=tf.losses.sigmoid_cross_entropy,
              metrics=[metrics.binary_accuracy]) 

In [189]:
history = model.fit(train_X, train_Y, batch_size=2, epochs=100, verbose=1)

Epoch 1/100
7/7 [==============================] - 0s 1ms/sample - loss: 0.7632 - categorical_accuracy: 0.7143
Epoch 2/100
7/7 [==============================] - 0s 1ms/sample - loss: 0.7190 - categorical_accuracy: 0.7143
Epoch 3/100
7/7 [==============================] - 0s 1ms/sample - loss: 0.7250 - categorical_accuracy: 0.7143
Epoch 4/100
7/7 [==============================] - 0s 1ms/sample - loss: 0.7360 - categorical_accuracy: 0.7143
Epoch 5/100
7/7 [==============================] - 0s 997us/sample - loss: 0.7250 - categorical_accuracy: 0.7143
Epoch 6/100
7/7 [==============================] - 0s 1ms/sample - loss: 0.7049 - categorical_accuracy: 0.7143
Epoch 7/100
7/7 [==============================] - 0s 1ms/sample - loss: 0.7092 - categorical_accuracy: 0.5714
Epoch 8/100
7/7 [==============================] - 0s 1ms/sample - loss: 0.6801 - categorical_accuracy: 0.5714
Epoch 9/100
7/7 [==============================] - 0s 1ms/sample - loss: 0.6754 - categorical_accuracy: 0.8571

7/7 [==============================] - 0s 997us/sample - loss: 0.3071 - categorical_accuracy: 1.0000
Epoch 74/100
7/7 [==============================] - 0s 1ms/sample - loss: 0.3104 - categorical_accuracy: 1.0000
Epoch 75/100
7/7 [==============================] - 0s 1ms/sample - loss: 0.3067 - categorical_accuracy: 1.0000
Epoch 76/100
7/7 [==============================] - 0s 1ms/sample - loss: 0.3182 - categorical_accuracy: 0.8571
Epoch 77/100
7/7 [==============================] - 0s 997us/sample - loss: 0.3140 - categorical_accuracy: 0.8571
Epoch 78/100
7/7 [==============================] - 0s 997us/sample - loss: 0.3194 - categorical_accuracy: 0.8571
Epoch 79/100
7/7 [==============================] - 0s 1ms/sample - loss: 0.2987 - categorical_accuracy: 1.0000
Epoch 80/100
7/7 [==============================] - 0s 997us/sample - loss: 0.2965 - categorical_accuracy: 1.0000
Epoch 81/100
7/7 [==============================] - 0s 997us/sample - loss: 0.3108 - categorical_accuracy: 1.

In [190]:
result = model.evaluate(test_X, test_Y)

print('loss (cross-entropy) :', result[0])
print('test accuracy :', result[1])

3/3 [==============================] - 0s 0s/sample - loss: 14.8983 - categorical_accuracy: 0.0000e+00
loss (cross-entropy) : 14.898303985595703
test accuracy : 0.0


In [172]:
pred_X = np.array([11, 12, 13]).reshape(-1, 1)

In [173]:
np.argmax(model.predict(test_X), axis=1)

array([0, 0, 0], dtype=int64)

#### Classifier2

In [175]:
from keras.utils import np_utils

data_X = np.arange(10).reshape(-1, 1).astype('float32')
data_Y = np.array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5]).astype('float32')
data_Y = np_utils.to_categorical(data_Y, 6)
# print(data_Y)

In [176]:
train_X, test_X, train_Y, test_Y = model_selection.train_test_split\
(data_X, data_Y, test_size=0.3, random_state=0)
print(train_X.shape)
print(test_X.shape)
print(test_Y.shape)
print(test_Y)

(7, 1)
(3, 1)
(3, 6)
[[0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [178]:
model = models.Sequential() 

model.add(layers.Dense(input_dim=1, units=128, activation=None)) 
# model.add(layers.BatchNormalization()) # Use this line as if needed
model.add(layers.Activation('relu')) # layers.ELU or layers.LeakyReLU

model.add(layers.Dense(units=128, activation=None)) 
model.add(layers.Activation('relu')) 

model.add(layers.Dense(units=64, activation=None)) 
model.add(layers.Activation('relu'))

model.add(layers.Dense(units=6, activation='softmax')) # One-hot vector for 0 & 1

In [179]:
model.compile(optimizer=optimizers.Adam(), 
              loss='categorical_crossentropy',
              metrics=[metrics.categorical_accuracy]) 

In [182]:
history = model.fit(train_X, train_Y, batch_size=5, epochs=100, verbose=1)

Epoch 1/100
7/7 [==============================] - 0s 1ms/sample - loss: 1.2325 - categorical_accuracy: 0.4286
Epoch 2/100
7/7 [==============================] - 0s 570us/sample - loss: 1.2220 - categorical_accuracy: 0.4286
Epoch 3/100
7/7 [==============================] - 0s 568us/sample - loss: 1.2218 - categorical_accuracy: 0.4286
Epoch 4/100
7/7 [==============================] - 0s 570us/sample - loss: 1.2206 - categorical_accuracy: 0.4286
Epoch 5/100
7/7 [==============================] - 0s 704us/sample - loss: 1.2083 - categorical_accuracy: 0.5714
Epoch 6/100
7/7 [==============================] - 0s 717us/sample - loss: 1.2048 - categorical_accuracy: 0.4286
Epoch 7/100
7/7 [==============================] - 0s 712us/sample - loss: 1.1867 - categorical_accuracy: 0.5714
Epoch 8/100
7/7 [==============================] - 0s 570us/sample - loss: 1.1803 - categorical_accuracy: 0.7143
Epoch 9/100
7/7 [==============================] - 0s 561us/sample - loss: 1.1769 - categorical_ac

Epoch 73/100
7/7 [==============================] - 0s 570us/sample - loss: 0.8767 - categorical_accuracy: 0.4286
Epoch 74/100
7/7 [==============================] - 0s 427us/sample - loss: 0.8719 - categorical_accuracy: 0.4286
Epoch 75/100
7/7 [==============================] - 0s 427us/sample - loss: 0.8656 - categorical_accuracy: 0.7143
Epoch 76/100
7/7 [==============================] - 0s 722us/sample - loss: 0.8615 - categorical_accuracy: 0.7143
Epoch 77/100
7/7 [==============================] - 0s 428us/sample - loss: 0.8466 - categorical_accuracy: 0.7143
Epoch 78/100
7/7 [==============================] - 0s 569us/sample - loss: 0.8429 - categorical_accuracy: 0.7143
Epoch 79/100
7/7 [==============================] - 0s 570us/sample - loss: 0.8372 - categorical_accuracy: 0.8571
Epoch 80/100
7/7 [==============================] - 0s 561us/sample - loss: 0.8350 - categorical_accuracy: 0.7143
Epoch 81/100
7/7 [==============================] - 0s 573us/sample - loss: 0.8309 - cat

In [186]:
result = model.evaluate(test_X, test_Y)

print('loss (cross-entropy) :', result[0])
print('test accuracy :', result[1])

3/3 [==============================] - 0s 0s/sample - loss: 4.5187 - categorical_accuracy: 0.0000e+00
loss (cross-entropy) : 4.51867151260376
test accuracy : 0.0


In [187]:
pred_X = np.array([11, 12, 13]).reshape(-1, 1)

In [188]:
np.argmax(model.predict(test_X), axis=1)

array([2, 5, 2], dtype=int64)